server:
  port: 8080
spring:
 application:
   name: first
logging:
 pattern: 
   console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
   file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
 level: 
   org.springframework.web: DEBUG
 file:
   app.log
name: param
my:
  servers:
    - dev.bar.com
    - foo.bar.com
management:
  scurity:
     enabled:false
    